#%RAML 1.0 NamedExample
value:
  - id: "1"
    firstName: "shubham"
    lastName: "saxena"
    address: "wakad"
    postal: "41004"
    country: "india"
    miles: 23
    creationDate: "2016-01-04T12:48:19+00:00"
    accType: "personal"
  - id: "2"
    firstName: "dssdsd"
    lastName: "rercdf"
    address: "wakadd"
    postal: "41014"
    country: "india"
    miles: 213
    creationDate: "2016-01-04T12:48:19+00:00"
    accType: "personal"